DROP TABLE measure_type;

CREATE TABLE measure_type (
  measure_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

COMMENT ON COLUMN measure_type.measure_type_id IS 'Measute type idetity';
COMMENT ON COLUMN measure_type.name IS 'Name of measute type';

ALTER TABLE measure_type OWNER TO measurements_owner;

DROP TABLE units;

CREATE TABLE units (
  unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

COMMENT ON COLUMN units.units_id IS 'Units type idetity';
COMMENT ON COLUMN units.name IS 'Name of measute type';

ALTER TABLE units OWNER TO measurements_owner;

CREATE TABLE measurements (
  measurement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id TEXT,
  measure_type_id INTEGER,
  unit_id INTEGER,
  value REAL,
  measured_at TIMESTAMP,

  CONSTRAINT fk_units
    FOREIGN KEY (unit_id)
    REFERENCES units(unit_id),

  CONSTRAINT fk_measure_type
    FOREIGN KEY (measure_type_id)
    REFERENCES measure_type (measure_type_id)
);

COMMENT ON COLUMN measurements.measurement_id IS 'Measurement identity';
COMMENT ON COLUMN measurements.sensor_id is 'Sensor identity';
COMMENT ON COLUMN measurements.measure_type_id is 'Reference to measure_type';
COMMENT ON COLUMN measurements.units_id is 'Reference to units';
COMMENT ON COLUMN measurements.value is 'Measurement value';
COMMENT ON COLUMN measurements.measured_at is 'Measurement timestamp';

ALTER TABLE measurements OWNER TO measurements_owner;

GRANT INSERT ON measurements TO meter;

INSERT INTO units (name) VALUES ('Pa');

INSERT INTO measure_type (name) VALUES ('Pressure');
