name: Deploy Go API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Build Go application
        run: | 
          GOOS=linux GOARCH=amd64 go build -o measure-api-service ./cmd/api/main.go
      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          connect_timeout: 10s
          first_ssh: |
            sudo systemctl stop measure-api-service || true
            sudo chown -R ${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_HOST }} /opt/measure-api-service/
            sudo chmod 755 /opt/measure-api-service
            sudo rm -rf /opt/measure-api-service/*
          scp: |
            measure-api-service => /opt/measure-api-service/
            config/config.yml => /opt/measure-api-service/config
          last_ssh: |
            sudo chown -R measure-api-service:measure-api-service /opt/measure-api-service/
            sudo chmod 755 /opt/measure-api-service
            sudo systemctl start measure-api-service
