name: Deploy Go API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Build Go application
        run: | 
          GOOS=linux run: GOARCH=amd64 go build -o measure-api-service ./cmd/api
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl stop measure-api-service || true
            sudo cp $GITHUB_WORKSPACE/measure-api-service /opt/measure-api-service/
            sudo cp $GITHUB_WORKSPACE/config/config.yml /opt/measure-api-service/
            sudo chown -R api-service:api-service /opt/api-service/
            sudo chmod 755 /opt/api-service/measure-api-service
            sudo systemctl measure-start api-service
