name: Deploy Go API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Build Go application
        run: | 
          GOOS=linux GOARCH=amd64 go build -o measure-api-service ./cmd/api/main.go
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "measure-api-service,config/config.yml"
          target: "/opt/measure-api-service/"
          overwrite: true
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl stop measure-api-service || true
            sudo chown -R measure-api-service:measure-api-service /opt/measure-api-service/
            sudo chmod 755 /opt/measure-api-service
            sudo systemctl start measure-api-service
